### ISSUE TITLE
Epic: Reorganize website

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/enhancements#108]
## Epic Description

The website has grown incrementally without any overall design. To make it more clear and usable, and to ease future website contributions, we should agree on an overall website layout.

## Acceptance Criteria

A more usable design is created, agreed on, and implemented.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

* [ ] Design layout, get consensus - #21 
* [ ] Incrementally implement design

**Comment by dfarrell07** [comment]
This isn't ready for 0.13, moving off board for now, will continue trying to iterate on design during this release.

**Comment by dfarrell07** [comment]
This is a very old idea, I think if we want to reorganize the website we'd like to start over from a fresh plan.
