### ISSUE TITLE
Epic: Support submariner on ROSA 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/enhancements#133]
## Epic Description

Support connecting multiple OCP clusters on ROSA using Submariner.
## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

- [x] Verify if LB mode is working fine with ROSA clusters
- [x] Run e2e tests on ROSA 
- [x] [Issue labelling node on ROSA](https://github.com/submariner-io/submariner/issues/1896)
- [x] [Issue with subctl join on ROSA ](https://github.com/submariner-io/subctl/issues/117)
- [x] Document steps for SM deployment on ROSA 
- [x] Deploy Submariner from ACM 
- [x]  [Issue with addon when applying SubmarinerConfig CR for ROSA ](https://github.com/stolostron/submariner-addon/issues/509)
- [ ] [MTU issue between ROSA and AWS](https://github.com/submariner-io/submariner/issues/2043)
- [x] [scc issue when ROSA deployed from ACM](https://github.com/stolostron/submariner-addon/issues/525)

**Comment by yboaron** [comment]
I'm going to close this epic , we'll track open tasks as separate issues.
