### ISSUE TITLE
Epic: Support submariner on ARO

### ISSUE THREAD

**Issue by yboaron** [submariner-io/enhancements#135]
## Epic Description

Support connecting multiple OCP clusters on ARO using Submariner.
## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

- [X] Verify if LB mode is working fine with ARO clusters
- [X] Run e2e tests on ARO 
- [x] Document steps for SM deployment on ARO from ACM
- [X] Deploy Submariner from ACM 
- [X] [Issue with addon when applying SubmarinerConfig CR for ARO](https://github.com/stolostron/submariner-addon/issues/529)

**Comment by yboaron** [comment]
I'm going to close this epic , we'll track open tasks as separate issues.
