### ISSUE TITLE
[EPIC] Option for recovering the broker-info.subm file from a running broker cluster

### ISSUE THREAD

**Issue by josecastillolema** [submariner-io/enhancements#143]
**Epic Description**

**What would you like to be added**:
It would be nice to have a `subctl` subcommand (or a well defined procedure) to recover the `broker-info.subm` from a running broker cluster.

**Why is this needed**:
There may be situations were the `broker-info.subm` file gets lost over time.

**Acceptance Criteria**
`broker-info.subm` file can be successfully recovered from the user specified environment.

## Definition of Done (Checklist)

* [x] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items

- [x] Add a new `subctl` command to recover `broker-info.subm`
- [x] Add logic in `pkg/broker` to fetch the data
- [x] Add system tests
- [x] Add release notes
- [x] Add explanation in the website

##  PRs
Depends on https://github.com/submariner-io/subctl/pull/467
Depends on https://github.com/submariner-io/subctl/pull/588
Depends on https://github.com/submariner-io/subctl/pull/621
Depends on https://github.com/submariner-io/subctl/pull/630
Depends on https://github.com/submariner-io/submariner-website/pull/910
Depends on https://github.com/submariner-io/enhancements/pull/173
Depends on https://github.com/submariner-io/subctl/pull/649

**Comment by nyechiel** [comment]
@Jaanki any reason to keep this open or is it fully done now?
