### ISSUE TITLE
Sync RBACs b/w subctl and operator

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/enhancements#181]
## Epic Description
Currently, RBACs for Broker are defined in both subctl and operator repo. Its confusing and difficult to manage 2 copies of the same permission.

This epic aims to remove the permissions defined in subctl and use the ones from operator. Also these RBACs need to be embedded so that they can be used by subctl.

## Acceptance Criteria
RBACs permission should be as duplicated as possible.

## Definition of Done (Checklist)
* [x] Code complete
* [x] Relevant metrics added
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [x] Deployed using ACM/OCM addon
* [x] Deploy using Helm
* [x] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [x] Run subctl verify, diagnose and gather
* [x] Uninstall
* [x] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items
Depends on https://github.com/submariner-io/subctl/pull/653
Depends on https://github.com/submariner-io/submariner-operator/pull/2552
Depends on https://github.com/submariner-io/submariner-operator/issues/2553
Depends on https://github.com/submariner-io/subctl/issues/685
Depends on https://github.com/submariner-io/submariner-operator/pull/2602

**Comment by Jaanki** [comment]
All dependent issues/PR are closed. Closing this as done.
