### ISSUE TITLE
Add subctl upgrade command

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/enhancements#183]
## Epic Description
A new `subctl upgrade` command should be added that upgrades the running enviroment to the version specified by the user. The command would do the following:

1. Upgrade subctl itself to the specified version
2. Upgrade Submariner to the specified version by re-running `deploy-broker` and `join`.

What it won't do is to change from a non-globalnet environment to globalnet enabled one or vice-versa. Feasibility of adding or removing the Service discovery component needs to be determined.

This is helpful in major and minor version upgrades.

## Acceptance Criteria
Submariner environment can be successfully upgraded to the specified version.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items

- [ ] Write logic to upgrade subctl
- [ ] Add rerunning `deploy-broker` command with the specified Submariner version
- [ ] Add rerunning `join` command with the specified Submariner version

**Comment by skitt** [comment]
Release notes and documentation: https://github.com/submariner-io/submariner-website/pull/1009
