### ISSUE TITLE
OVN InterConnect support

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#186]
## Epic Description
OVN InterConnect support

The OVN is moving to a new architecture using an OVN interconnect. This would have an impact on Submariner. We need to test Submariner with the new implementation and make the necessary changes.

## Acceptance Criteria
* Submariner should work with OVN IC setups
* Submariner should work with OVN setups without IC
* Upgrades should work without any issues.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
* [x] submariner-io/enhancements#142
* [x] submariner-io/enhancements#187
* [x] submariner-io/submariner-operator#2691
* [x] #203
* [x] submariner-io/enhancements#188
* [x] submariner-io/submariner#2496
* [x] submariner-io/enhancements#190
* [x] submariner-io/enhancements#191
* [x] submariner-io/enhancements#194
* [x] submariner-io/enhancements#192
* [x] submariner-io/enhancements#193

**Comment by aswinsuryan** [comment]
The documentation and CI are tracked with these issues

#206 
 #209
