### ISSUE TITLE
Add Nftables support

### ISSUE THREAD

**Issue by yboaron** [submariner-io/enhancements#214]
## Epic Description

Nftables, abbreviated as "netfilter tables," represents a contemporary replacement for iptables, specifically crafted to align with the requirements of modern networking environments.

Starting with iptables version 1.8.0, it supports a new mode (a.k.a iptables-nft) that uses nftables APIs of the kernel while preserving the same original iptables user-facing API. Most of the linux distributions now-a-days allow us to use iptables-nft or iptables-legacy but default to iptables-nft.

This epic captures the changes necessary in various Submariner components for supporting Nftables based platforms.
## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

* [X] Document covering proposed high level design for Nftables support
* [X] Refactor iptables package under packetfilter
* [X] Refactor ipset package under packetfilter
* [x] Control Iptables/Nftables configuration
* [X] Deliver Submariner (no Nftables support) with the new  packetfilter package
* [X] Extend packetfilter package to support Nftables
* [ ] Upgrade
* [x] Testing with Nftables driver in packet_filter

**Comment by maayanf24** [comment]
@yboaron - Are you preparing an ep for this epic?

**Comment by yboaron** [comment]
[High Level Design document](https://docs.google.com/document/d/1PAjU61XUGaQ2qZZu_66clxadC997lsBGYcjydYEayR0/edit?usp=sharing)

**Comment by yboaron** [comment]
@maayanf24 Nope, we are not preparing ep for this epic, all the relevant details covered in [this doc](https://docs.google.com/document/d/1Zenkqelw3GqSYRQ7W5OzamhEu1Ty_EHzryYTfe0udYE/edit?usp=sharing)
