### ISSUE TITLE
Add support for clusterset IP for MCS Compliance

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#229]
## Epic Description
While Submariner/Lighthouse implements the MCS API, it is not compliant in that there is no clusterset IP assigned in the ServiceImport.

While there are design reasons mostly to do with perf and scale, there are compelling use cases to have Submariner provide an implementation that is compliant with MCS API in this respect. e.g. Istio with Submariner.

## Acceptance Criteria
Submariner deployment is compliant with MCS API wrt clusterset IP assignment.

Any MCS SIG compliance tests that can serve as acceptance tests? Yes

## Definition of Done (Checklist)

* [x] Code complete
* [ ] ~Relevant metrics added~
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [x] Deploy using Helm
* [ ] ~Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)~
* [x] Run subctl verify, diagnose and gather
* [ ] ~Uninstall~
* [x] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items

* [x] [Enhancement Proposal with all the changes required for MCS Compliance mode](https://github.com/submariner-io/enhancements/pull/230)
* [x] [Changes to Submariner and/or ServiceDiscovery CRs to add option for MCS mode](https://github.com/submariner-io/submariner-operator/pull/3210)
* [x] [Changes to Lighthouse Agent](https://github.com/submariner-io/lighthouse/pull/1639)
* [x] [Changes to Lighthouse CoreDNS](https://github.com/submariner-io/lighthouse/pull/1641)
* [x] [Changes to Submariner-Operator to deploy Lighthouse in MCS Compliance mode](https://github.com/submariner-io/submariner-operator/pull/3217)
* [x] [Changes to Submariner-Operator to create ConfigMap to store the allocated clusterset CIDRs](https://github.com/submariner-io/submariner-operator/pull/3230)
* [x] [Changes to subctl](https://github.com/submariner-io/subctl/pull/1231)
* [x] [Lighthouse E2E test](https://github.com/submariner-io/lighthouse/pull/1643)
* [x] [Changes to the helm charts](https://github.com/submariner-io/submariner-charts/pull/561)

**Comment by tpantelis** [comment]
> 2. EndpointSlices do not contain individual Pod IPs but ClusterIP of services in that cluster.

Looking at https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#tracking-endpoints, I don't see where it explicitly states that `EndpointSlices` have to contain individual Pod IPs. But perhaps I'm missing something.

Also it's optional to even use `EndpointSlices`.

BTW, I'm not saying we can't/shouldn't expose the Pod IPs  - just pointing out that I don't think we're  non-compliant.

**Comment by tpantelis** [comment]
For 1), a prior [issue](https://github.com/submariner-io/lighthouse/issues/1350) was reported but went stale.

For 2), it was previously [discussed here](https://github.com/submariner-io/lighthouse/discussions/1269).

**Comment by vthapar** [comment]
The spec mentions this:
```
One or more EndpointSlice resources will exist for the exported Service, with each EndpointSlice containing only endpoints from a single source cluster.
```
Here it does say that EndpointSlice should contain Endpoints from that cluster. ES are optional for an implementation but spec mentions that if created they should contain endpoints, which basically means pod ips.

Should we reword the Epic? It is more a use case from Istio, but I wanted to use a generic wording.

**Comment by tpantelis** [comment]
> Here it does say that EndpointSlice should contain Endpoints from that cluster. ES are optional for an implementation but spec mentions that if created they should contain endpoints, which basically means pod ips.

I guess it's a matter of semantics. Generically an "_endpoint is an API object that acts as a bridge between a service and the pods that fulfill that service's requests_". However I don't think that necessarily means it has to be an actual pod IP - in our case it's the service VIP that indirectly leads to the backing pods.

I think the key point in that statement is that the endpoints contained in an EPS, whatever they are/represent, must all be from the same cluster.

> Should we reword the Epic? It is more a use case from Istio, but I wanted to use a generic wording.

We can mention the use case is for Istio (which we just did :)).
