### ISSUE TITLE
Provide ARM64 support

### ISSUE THREAD

**Issue by skitt** [submariner-io/enhancements#46]
## Epic Description

We want to provide out-of-the-box support for ARM64. Submariner should just work on ARM64 nodes, with no special configuration by the administrator or end-user.

## Acceptance Criteria

- [x] All the Submariner components can be deployed on ARM64 nodes
- [x] All the Submariner components work with each other regardless of individual nodes’ architectures (_e.g._ an x86 route agent connected to an ARM64 gateway, or failover from an x86 gateway to an ARM64)
- [x] Submariner gateways can connect to other-arch gateways

## Definition of Done (Checklist)

* [x] Code complete
* [ ] The acceptance criteria met
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [x] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [x] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [x] Release notes added

## Work Items

- [x] ensure all our dependencies are available on ARM64;
- [x] ensure we can build all our artifacts for ARM64;
- [x] ensure the images we push provide multi-arch manifests;
- [x] run tests on all the platforms we care about (assuming we have GHA support for them).

Depends on https://github.com/submariner-io/submariner/pull/1772
Depends on https://github.com/submariner-io/lighthouse/pull/694
Depends on https://github.com/submariner-io/submariner-operator/pull/2021
Depends on https://github.com/submariner-io/subctl/pull/66

**Comment by skitt** [comment]
This is blocked on re-reviews.

**Comment by nyechiel** [comment]
@skitt I am assuming we want to get https://github.com/submariner-io/lighthouse/pull/694 and https://github.com/submariner-io/subctl/pull/66 into 0.13? If so, can you please add them to the project board and ensure they get reviewed? 

Also, do we need to keep this tracking issue open or can we close at this point?

**Comment by skitt** [comment]
https://github.com/submariner-io/lighthouse/pull/694 was already on the board, I’ve added https://github.com/submariner-io/subctl/pull/66. I’ll keep pinging people until they are merged.

Let’s keep this open until it’s all done...

**Comment by nyechiel** [comment]
@skitt I think it's done now?

**Comment by skitt** [comment]
> @skitt I think it's done now?

I want to check the output of `subctl diagnose` and `subctl gather` to see if we need to add anything there. The documentation might need to be updated too.

**Comment by nyechiel** [comment]
> > @skitt I think it's done now?
> 
> I want to check the output of `subctl diagnose` and `subctl gather` to see if we need to add anything there. The documentation might need to be updated too.

Makes sense. Thanks for thinking about these. In general, I think it's better to open individual issues to track concrete, small tasks (once we know what they should be). Things tend to get lost within big epics.

**Comment by skitt** [comment]
Tracked in https://github.com/submariner-io/subctl/issues/122, https://github.com/submariner-io/subctl/issues/123, https://github.com/submariner-io/subctl/issues/124, and https://github.com/submariner-io/submariner-website/issues/782.
