### ISSUE TITLE
Support connecting multiple OCP clusters on RHOS using Submariner

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#47]
## Epic Description
Support connecting multiple OCP clusters on RHOS using Submariner.
Why is this needed:
The aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

## Acceptance Criteria
Should be able to prepare and deploy submariner in RHOS using subctl and cloud-prepare.

## Definition of Done (Checklist)

* [x] Code complete
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [x] Deployed using ACM/OCM addon
* [x] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [x] Run subctl verify, diagnose and gather
* [x] Uninstall
* [x] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items

- [x] Deploy using cloud prepare and subctl on existing OCP clusters on RHOS https://github.com/submariner-io/submariner-operator/issues/1725
- [x] Enhance cloud-prepare to support deploying dedicated Gateway nodes on RHOS - https://github.com/submariner-io/cloud-prepare/issues/167
- [x] Enhance cloud-prepare to support configuring existing worker nodes as GW nodes on RHOS -  https://github.com/submariner-io/cloud-prepare/issues/166
- [x] Deploy using OCM and submariner-addon
- [x] Add UT
- [x] Support and run subctl verify
- [x] Support and run subctl diagnose
- [x] Support and run subctl gather
- [x] Remove cluster from multcluster using subctl
- [x] Remove cluster from multicluster using OCM and submariner-addon
- [x] Uninstall submariner using subctl
- [x] Uninstall submariner using OCM and submariner-addon
- [x] UI support for troubleshooting etc. on OCM
- [x] [Documentation for deployments and removal using cloud-prepare and subctl](https://github.com/submariner-io/submariner-website/issues/702) 
- [x] Documentation for deployments and removal using OCM

**Comment by nyechiel** [comment]
See https://github.com/submariner-io/cloud-prepare/issues/19 for cloud-prepare

**Comment by nyechiel** [comment]
@aswinsuryan can you update this one please?

**Comment by aswinsuryan** [comment]
The addon and other tasks related to monitoring are pending.

**Comment by nyechiel** [comment]
> The addon and other tasks related to monitoring are pending.

Let's not also forget about docs.

**Comment by nyechiel** [comment]
@aswinsuryan I believe this is done at this point?

**Comment by aswinsuryan** [comment]
@nyechiel Yes this is done , closing it.
