### ISSUE TITLE
Support connecting multiple OCP clusters on ROSA using Submariner.

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#48]
## Epic Description
Support connecting multiple OCP clusters on ROSA using Submariner.
Why is this needed:
The aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

## Acceptance Criteria
Should be able to prepare and deploy submariner in ROSA using subctl and cloud-prepare.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

- [ ] Deploy using cloud prepare and subctl on existing OCP clusters on ROSA
- [ ] Enhance cloud-prepare to support deploying dedicated Gateway nodes on ROSA
- [ ] Enhance cloud-prepare to support configuring existing worker nodes as GW nodes on ROSA
- [ ] Deploy using OCM and submariner-addon
- [ ] Add UT
- [ ] Support and run subctl verify
- [ ] Support and run subctl diagnose
- [ ] Support and run subctl gather
- [ ] Remove cluster from multcluster using subctl
- [ ] Remove cluster from multicluster using OCM and submariner-addon
- [ ] Uninstall submariner using subctl
- [ ] Uninstall submariner using OCM and submariner-addon
- [ ] UI support for troubleshooting etc. on OCM
- [ ] Documentation for deployments and removal using cloud-prepare and subctl
- [ ] Documentation for deployments and removal using OCM

**Comment by maayanf24** [comment]
already done
