### ISSUE TITLE
Automated unjoin/uninstall

### ISSUE THREAD

**Issue by tpantelis** [submariner-io/enhancements#50]
## Epic Description

Add support to automatically "unjoin" a previously connected cluster by deleting/uninstalling all the Submariner-related components and removing dataplane rules programmed on the route agent and gateway nodes.

This is a common request from users. A manual process is documented [here](https://submariner.io/operations/cleanup/). 

The uninstall process should be able to be initiated via a `subctl` command and also via the Submariner ACM add-on.

For dataplane cleanup, [this blog](http://blog.itaysk.com/2017/12/26/the-single-use-daemonset-pattern-and-prepulling-images-in-kubernetes)  describes how to run a one-time task on each node using a `DaemonSet` with an init container to run the task. We can create cleanup `DaemonSets` corresponding to each component (route agent, gateway engine etc). We can reuse the same images and pass an _UNINSTALL_ environment variable to initiate the cleanup.

The tricky part is how to invoke the cleanup `DaemonSets`. The logical place would be from the `Operator` controller. We could put a finalizer on the `Submariner` resource and, when it's being deleted, delete the normal component `DaemonSets` and create the cleanup `DaemonSets`. After the  cleanup `DaemonSets` have completed (ie are ready), remove the finalizer and let deletion of the `Submariner` resource proceed. 

If cleanup fails for a component, the `DaemonSet` init container pod would return a non-zero exit code causing K8s to restart the pod. The `Operator` controller can wait a certain amount of time, like 2 min,  for a cleanup `DaemonSet` to be ready. After that time it’s reasonable to assume the error isn’t transient so the `Operator` controller can remove the finalizer and let deletion of the `Submariner` resource proceed. It could leave the cleanup `DaemonSet` so the user can inspect the `DaemonSet` status to see what failed. Or it could delete the `DaemonSet` and we could create a K8s `Event` to report the failure, either from the `Operator` or the failing pod. In `subctl`, after `Submariner` is deleted, we can report the failure to the user. Any cleanup `DaemonSet` that failed will eventually get deleted along with the namespace regardless.

The one potential downside with this approach is if the `Operator` pod is deleted first and thus the controller is never triggered. This would also leave the finalizer and prevent the `Submariner` resource from being deleted. But we can document the proper sequence.

## Acceptance Criteria

Invoking the uninstall process should remove all Submariner-related components and artifacts in the cluster.

## Definition of Done (Checklist)

* [x] Code complete
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using subctl
* [x] Deployed using ACM/OCM addon
* [x] Documentation added
* [x] Release notes added

## Work Items

- [x] https://github.com/submariner-io/submariner-operator/issues/1722
- [x] https://github.com/submariner-io/submariner/pull/1664
- [x] https://github.com/submariner-io/submariner/issues/1635
- [x] https://github.com/submariner-io/submariner/issues/1636
- [x] https://github.com/submariner-io/submariner/issues/1637
- [x] https://github.com/submariner-io/submariner/pull/1691
- [x] https://github.com/submariner-io/lighthouse/pull/682
- [x] https://github.com/submariner-io/submariner-operator/issues/1797
- [x] https://github.com/submariner-io/submariner-operator/pull/1843
- [x] https://github.com/submariner-io/submariner-operator/issues/1723
- [x] https://github.com/open-cluster-management/submariner-addon/pull/242
- [x] https://github.com/submariner-io/submariner-operator/pull/1863
- [ ] Create a K8s `Event` if an uninstall pod fails
- [ ] In add-on on spoke, watch K8s `Events` in submariner NS and copy to the event recorder
- [x] https://github.com/submariner-io/submariner-website/issues/684 (@tpantelis)

## Related Issues

- [ ] https://github.com/open-cluster-management/submariner-addon/issues/131
- [x] https://github.com/submariner-io/submariner/issues/1679
- [x] https://github.com/submariner-io/submariner-operator/issues/1270

**Comment by tpantelis** [comment]
[This blog](http://blog.itaysk.com/2017/12/26/the-single-use-daemonset-pattern-and-prepulling-images-in-kubernetes) describes how to run a job on each container using a DaemonSet.

**Comment by tpantelis** [comment]
@cmwylie19  Some notes/observations after studying the submariner add-on code a bit.

The add-on is bootstrapped by [deploying](https://github.com/open-cluster-management/submariner-addon/tree/main/deploy), on the hub, the [SubmarinerConfig CRD](https://github.com/open-cluster-management/submariner-addon/blob/main/deploy/olm-catalog/manifests/submarineraddon.open-cluster-management.io_submarinerconfigs.yaml) and a [Deployment](https://github.com/open-cluster-management/submariner-addon/blob/main/deploy/olm-catalog/manifests/submariner-addon.clusterserviceversion.yaml#L215) that runs the `submariner controller` process from the `submariner-addon` image.  This in turn invokes the [hub controller manager](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/manager.go#L83) that starts several controllers including:

- [ManagedClusterAddOn Manager](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/manager.go#L169) - watches `ManagedClusterAddOn` resources and, on creation of the submariner `ManagedClusterAddOn`, creates a [ManifestWork](https://open-cluster-management.io/concepts/manifestwork/) resource with the workload [manifests](https://github.com/open-cluster-management/submariner-addon/tree/main/pkg/hub/submarineraddonagent/manifests) supplied by the [AgentAddon](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineraddonagent/agent.go#L87) implementation.  The resulting resources are subsequently deployed on the managed cluster (or spoke). Of note is the [Deployment](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineraddonagent/manifests/deployment.yaml) that runs the [submariner add-on spoke agent](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/spoke/agent.go). These resources are owned by the `ManifestWork` and thus automatically garbage collected.
- [Submariner Agent Controller](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/controller.go) - watches several resources including the submariner `ManagedClusterAddOn`. It creates another `ManifestWork` that deploys the [submariner Operator](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/manifests/operator/submariner-operator-subscription.yaml) via an OperatorHub `Subscription` (unclear how this mechanism works) and the [Submariner](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/manifests/operator/submariner.io-submariners-cr.yaml) resource on the managed cluster.  It adds a finalizer to the `ManagedClusterAddOn` and, on pending deletion, it deletes the `ManifestWork`.

If we can guarantee that the `Submariner` resource is deleted before the OperatorHub `Subscription` then we could have the submariner `Operator` add a finalizer to the `Submariner` resource and invoke the dataplane cleanup. We might be able to  accomplish this by moving the `Submariner` resource into a separate `ManifestWork` and deleting it first. I assume the `Operator` installs the `Submariner` CRD in which case that `ManifestWork` would have to be deployed first.

**Note**: [this doc](https://open-cluster-management.io/concepts/manifestwork/) states that "_When ManifestWork is deleted, work agent runs a Foreground deletion, that ManifestWork will stay in deleting state until all its related resources has been fully cleaned in the managed cluster._". Assuming we can rely on that (looking at the [code](https://github.com/open-cluster-management-io/work/tree/main/pkg/spoke/controllers), that seems to be the case), the `Submariner` finalizer should guarantee that, when the `ManifestWork` is finally deleted, the submariner `Operator` controller has completed its cleanup.

**Comment by ghost** [comment]
> @cmwylie19 Some notes/observations after studying the submariner add-on code a bit.
> 
> The add-on is bootstrapped by [deploying](https://github.com/open-cluster-management/submariner-addon/tree/main/deploy), on the hub, the [SubmarinerConfig CRD](https://github.com/open-cluster-management/submariner-addon/blob/main/deploy/olm-catalog/manifests/submarineraddon.open-cluster-management.io_submarinerconfigs.yaml) and a [Deployment](https://github.com/open-cluster-management/submariner-addon/blob/main/deploy/olm-catalog/manifests/submariner-addon.clusterserviceversion.yaml#L215) that runs the `submariner controller` process from the `submariner-addon` image. This in turn invokes the [hub controller manager](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/manager.go#L83) that starts several controllers including:
> 
> * [ManagedClusterAddOn Manager](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/manager.go#L169) - watches `ManagedClusterAddOn` resources and, on creation of the submariner `ManagedClusterAddOn`, creates a [ManifestWork](https://open-cluster-management.io/concepts/manifestwork/) resource with the workload [manifests](https://github.com/open-cluster-management/submariner-addon/tree/main/pkg/hub/submarineraddonagent/manifests) supplied by the [AgentAddon](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineraddonagent/agent.go#L87) implementation.  The resulting resources are subsequently deployed on the managed cluster (or spoke). Of note is the [Deployment](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineraddonagent/manifests/deployment.yaml) that runs the [submariner add-on spoke agent](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/spoke/agent.go). These resources are owned by the `ManifestWork` and thus automatically garbage collected.
> * [Submariner Agent Controller](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/controller.go) - watches several resources including the submariner `ManagedClusterAddOn`. It creates another `ManifestWork` that deploys the [submariner Operator](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/manifests/operator/submariner-operator-subscription.yaml) via an OperatorHub `Subscription` (unclear how this mechanism works) and the [Submariner](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/manifests/operator/submariner.io-submariners-cr.yaml) resource on the managed cluster.  It adds a finalizer to the `ManagedClusterAddOn` and, on pending deletion, it deletes the `ManifestWork`.
> 
> If we can guarantee that the `Submariner` resource is deleted before the OperatorHub `Subscription` then we could have the submariner `Operator` add a finalizer to the `Submariner` resource and invoke the dataplane cleanup. We might be able to accomplish this by moving the `Submariner` resource into a separate `ManifestWork` and deleting it first. I assume the `Operator` installs the `Submariner` CRD in which case that `ManifestWork` would have to be deployed first.
> 
> **Note**: [this doc](https://open-cluster-management.io/concepts/manifestwork/) states that "_When ManifestWork is deleted, work agent runs a Foreground deletion, that ManifestWork will stay in deleting state until all its related resources has been fully cleaned in the managed cluster._". Assuming we can rely on that (looking at the [code](https://github.com/open-cluster-management-io/work/tree/main/pkg/spoke/controllers), that seems to be the case), the `Submariner` finalizer should guarantee that, when the `ManifestWork` is finally deleted, the submariner `Operator` controller has completed its cleanup.

I'm still digging into the codebase but it appears as though the mechanism for installing the `submariner-operator` subscription is through the `SubmarinerConfig` [resource](https://github.com/open-cluster-management/submariner-addon/blob/main/docs/submarinerConfig.md).  I could be way off.

[In this document](https://github.com/open-cluster-management/submariner-addon/blob/main/docs/submarinerConfig.md), 5 & 6 under use cases seem to demonstrate how to change the default submariner-operator subscriptions. 

In the [Submariner Agent Controller](https://github.com/open-cluster-management/submariner-addon/blob/01028e82edaee45fc980ccbcab02963216ba96ce/pkg/hub/submarineragent/controller.go#L206), I am seeing references to `SubmarinerConfigs` which should be used to deploy the `Subscription`.

I wonder if there is a possibility to append another finalizer to the `SubmarinerConfig` to keep it safe from deletion when the `submariner` resource is deleted, then have the `submariner-operator` add a finalizer to the Submariner resource and invoke the dataplane cleanup?

**Comment by tpantelis** [comment]
> 
> I'm still digging into the codebase but it appears as though the mechanism for installing the `submariner-operator` subscription is through the `SubmarinerConfig` [resource](https://github.com/open-cluster-management/submariner-addon/blob/main/docs/submarinerConfig.md). I could be way off.
> 
> [In this document](https://github.com/open-cluster-management/submariner-addon/blob/main/docs/submarinerConfig.md), 5 & 6 under use cases seem to demonstrate how to change the default submariner-operator subscriptions.
> 
> In the [Submariner Agent Controller](https://github.com/open-cluster-management/submariner-addon/blob/01028e82edaee45fc980ccbcab02963216ba96ce/pkg/hub/submarineragent/controller.go#L206), I am seeing references to `SubmarinerConfigs` which should be used to deploy the `Subscription`.
> 
> I wonder if there is a possibility to append another finalizer to the `SubmarinerConfig` to keep it safe from deletion when the `submariner` resource is deleted, then have the `submariner-operator` add a finalizer to the Submariner resource and invoke the dataplane cleanup?

The `SubmarinerConfig` enables the end user to customize the Submariner deployment, including the Operator `Subscription` configuration. But the `SubmarinerConfig` is not required for deployment, defaults are used if it is [not present](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarinerbrokerinfo/brokerinfo.go#L136).

The controller already [adds a finalizer](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/controller.go#L343) to the `SubmarinerConfig` to clean up the cloud environment.

It's interesting to note that, while the `SubmarinerConfig` isn't needed to deploy the submariner `Operator`, it is needed to [administer the cloud environment](https://github.com/open-cluster-management/submariner-addon/blob/main/pkg/hub/submarineragent/controller.go#L371) in order for submariner to work properly. This seems inconsistent.  So it seems the front-end always creates a `SubmarinerConfig` and that the code is handling timing where the `ManagedClusterAddOn` is created first. That's OK but I'm not sure why it doesn't wait until all the components are created before it deploys/administers anything to be consistent. Also if the `SubmarinerConfig` was created afterwards and its fields differed from the defaults then it would update the `ManifestWork` which, I assume, would re-deploy the OperatorHub `Subscription` which seems wasteful.

**Comment by nyechiel** [comment]
@tpantelis my understanding is that design work/high level plan was completed. Can you confirm what is the implementation plan? It would be great if you can break it into specific tasks and identify owners for each. We still want to complete it for 0.12 for both `subctl` and the addon.

**Comment by tpantelis** [comment]
> @tpantelis my understanding is that design work/high level plan was completed. Can you confirm what is the implementation plan? It would be great if you can break it into specific tasks and identify owners for each. We still want to complete it for 0.12 for both `subctl` and the addon.

I specified the work items above. I put down tentative owners for each - other folks are working on other things so I haven't gotten commitment from anyone else to work on this.
