### ISSUE TITLE
Support Globalnet deployment in ACM/OCM

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/enhancements#51]
## Epic Description
Currently, ACM/OCM only supports deploying Vanilla Submariner, and it's not possible to deploy Globalnet.
This EPIC is to track the individual tasks associated to implement Globalnet in ACM.

Along with this, we also want to address the [remaining bits](https://github.com/submariner-io/submariner/issues/652) from the Globalnet 2.0 feature, primarily the metrics support and removing the dependency with the kube-proxy driver.

## Acceptance Criteria
One should be able to deploy Globalnet with ACM with all the e2e tests passing.

## Definition of Done (Checklist)
* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
The following are the individual work items for this feature.

- [x] Identify the metrics that needs to be supported in the new Globalnet 2.0 implementation.
- [x] [Implement the required metrics](https://github.com/submariner-io/submariner/issues/1471) Open issue - submariner-io/subctl#73
- [x] Analyse the possible solutions to remove the dependency with kubeproxy and finalize on one of them.
- [x] [Avoid dependency on the IPtable chains programmed by IPtables kube-proxy driver](https://github.com/submariner-io/submariner/issues/1166)
- [x] [Addon changes to support globalnet configuration while deploying Broker.](https://github.com/stolostron/submariner-addon/pull/286)
- [x] [GUI changes in ACM console while creating a clusterset/broker cluster.](https://github.com/stolostron/console/pull/1294)
- [x] Addon changes to support globalnet configuration while deploying managed clusters.
- [x] [Enhance subctl gather to collect logs for the new changes.](https://github.com/submariner-io/submariner/issues/1700)
- [x] [Enhance subctl diagnose to validate issues with Globalnet deployment](submariner-io/submariner-operator#1866)
- [x] [Unit/e2e tests](https://github.com/stolostron/submariner-addon/pull/286) 
- [x] [Document requirement of broker object in ACM docs](https://github.com/stolostron/rhacm-docs/pull/3174)
- [ ] Identify and document steps for manual installation (non GUI) of globalnet using ACM/OCM.
- [x] Document globalnet support in ACM docs.

**Comment by maayanf24** [comment]
@sridhargaddam can we close this?
If not, please move to the Backlog board

**Comment by sridhargaddam** [comment]
Pretty much all the activities planned as part of this EPIC are completed. We have PRs/issues to track the documentation work, so we can close this.
