### ISSUE TITLE
Submariner support for load-balancer mode

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/enhancements#52]
## Epic Description
Submariner load-balancer support

Currently, the load-balancer mode is an experimental feature in Submariner and is not well tested across various public and onPrem clusters. This EPIC is to understand the load-balancer implementations across AWS and GCP clouds to start with, finding any gaps and also its implications on HA-failover times.

## Acceptance Criteria
Identify and where applicable fix the missing gaps in order to make load balancer a supported feature.

* [ ] Code complete
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
The following are the individual work items for this feature.

- [x] Understand and if possible fix the issue with load balancer mode on AWS cloud.
      Related issue: https://github.com/submariner-io/submariner/issues/1410
                              https://github.com/submariner-io/submariner/issues/1484
- [x] [Periodic Public IP watcher for any changes in the external-ip](https://github.com/submariner-io/submariner/issues/1823)
- [ ] Analyze the HA failover time with load-balancer mode.
- [ ] Understand the implications on throughput when using the load balancer mode vs regular deployment.
- [x] Verify that load balancer mode works fine with GCP clusters.
- [x] [AWS: Loadbalancer mode not working with VxLAN Cable driver](https://github.com/submariner-io/submariner/issues/1822)
- [ ] [Update subctl cloud prepare for various clouds like AWS/GCP/Azure/OSP to support load-balancer mode](https://github.com/submariner-io/subctl/issues/14)
- [ ] [Issue with SM deployment after subctl prepare set number of gateways > 0 ](https://github.com/submariner-io/submariner/issues/1943 )
- [x] [Fix issue with public IP resolver](https://github.com/submariner-io/submariner/issues/1842)
- [x]  [Update subctl diagnose firewall inter-cluster ](https://github.com/submariner-io/submariner/issues/1849)
- [x]  [Issue with Loadbalancer mode when using three clusters](https://github.com/submariner-io/submariner/issues/1852)
- [x] Verify that Loadbalancer works with multiple nodes labelled as GW nodes.
- [ ] Verify if LB mode is working fine on SNO clusters.
- [x] Add support for LB services in KIND (MetalLB)
- [x] Verify that Loadbalancer works on ROSA 
- [x] Verify that Loadbalancer works on ARO

**Comment by sridhargaddam** [comment]
Related issue: https://github.com/submariner-io/submariner/issues/1410

**Comment by maayanf24** [comment]
@yboaron to update task list

**Comment by yboaron** [comment]
I think we can close this epic and track open tasks as separate issues.
@sridhargaddam @maayanf24 , WDYT ?

**Comment by maayanf24** [comment]
Sounds good. @yboaron Please make sure there are issues for all open tasks and then you can close this epic

**Comment by yboaron** [comment]
I opened this issue  https://github.com/submariner-io/subctl/issues/1417

**Comment by yboaron** [comment]
Going to close this issue
