### ISSUE TITLE
Epic: Restructure/refactor submariner-operator repo

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/enhancements#53]
## Epic Description
This will ensure that submariner-operator repo structure follows go standards and is optimised.

## Acceptance Criteria
submariner-operator code is as much optimised and modular as possible.

## Definition of Done (Checklist)

* [x] Code complete
* ~~[ ] Relevant metrics added~~
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* ~~[ ] Deployed using cloud-prepare+subctl~~
* ~~[ ] Deployed using ACM/OCM addon~~
* ~~[ ] Deploy using Helm~~
* ~~[ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)~~
* [x] Run subctl verify, diagnose and gather
* ~~[ ] Uninstall~~
* ~~[ ] Troubleshooting (gather/diagnose) added~~
* ~~[ ] Documentation added~~
* ~~[ ] Release notes added~~

## Work Items
- [x] Make subctl a library Depends on https://github.com/submariner-io/submariner-operator/issues/1329
