### ISSUE TITLE
Improve integration with submariner-addon

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/enhancements#54]
## Epic Description
Submariner addon should use submariner operator to manage submariner deployment on managed clusters. This allows for reusing of operator, automated management using operator and a single point of development efforts.

## Acceptance Criteria
addon uses operator to deploy broker and submariner on hub and spokes.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

- [ ] Depends on https://github.com/submariner-io/submariner-operator/issues/1040

**Comment by nyechiel** [comment]
Let's open concrete items we want to be focusing on.
