### ISSUE TITLE
Epic: Debuggability improvements

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/enhancements#57]
## Epic Description

Improve current troubleshooting documentation on Sumariner.io - [Troubleshooting docs](https://submariner.io/operations/troubleshooting/) 
Aim is to make it easy for support teams to troubleshoot and resolve the problems, or capture relevant information if unable to resolve.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

* [x] [Documentation - Add missing options in `subctl diagnose`](https://github.com/submariner-io/submariner-website/pull/608)
* [ ] Documentation - Add information on how to interpret `diagnose` output
* [ ] Documentation - Add more information on different `subctl gather` options
* [ ] Documentation - Add information on specific gather data to look at for different issues discovered by `diagnose`
* [ ] Documentation - Add manual troubleshooting steps for anything not covered by `diagnose`
* [ ] Documentation - More verbose output form `gather` and `diagnose`
* [ ] `subctl` - Handle multiple kubeconfigs/contexts better, avoid gathering information from same cluster repeatedly
* [ ] run `subctl diagnose` from a pod
* [ ] output from `subctl diagnose` should be capture in CR
* [ ] add metrics to reflect `subctl diagnose` running results
* [ ] `diagnose` -  Detect errors in cloud deployment
* [ ] `diagnose` -  Detect service discovery issues
* [ ] `diagnose` -  Detect cabledriver issues
* [ ] `gather` -  Gather logs from `submariner-addon` if OCM deployment
* [ ] `gather` -  Gather information from cloud e.g. ports opened etc.
* [ ] CI/CD - Add `subctl diagnose` to CI/CD in case of any test failure
* [ ] CI/CD - Use `subctl gather` in CI/CD post-mortem in case of any test failure
* [ ] CI/CD - Identify nature of failure in CI/CD to run subset of diagnose/gather and collect minimal information required.

**Comment by nyechiel** [comment]
@maayanf24 is this something you are planning to work on for 0.12?

**Comment by nyechiel** [comment]
@maayanf24 ^^

**Comment by nyechiel** [comment]
Some items landed in 0.12, some are not. Moving to the general backlog board so that we can further discuss this as part of 0.13 planning. This seems like a "collection of items" rather than an epic, and as such, I suggest to report specific issues and prioritize.. otherwise it would be hard to make more progress on this.

**Comment by maayanf24** [comment]
Will open separate issues for remaining work
