### ISSUE TITLE
Epic: CNCF Incubation/Graduation, CII Silver/Gold

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/enhancements#58]
## Epic Description

Prepare to apply for CNCF Incubation. Use CNCF Graduation and CII Silver/Gold as guidance for exceeding Incubation minimums and preparing for Graduating in less than two years from Incubating (per requirements).

## Acceptance Criteria

[CNCF Sandbox](https://github.com/submariner-io/submariner/issues/1297)
-  [x] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
   - Transferred  https://github.com/cncf/sandbox/issues/244#issuecomment-2376951839

[CNCF Incubation](https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#incubating-stage):
- Due diligence will be done during the Incubation reveiw https://github.com/cncf/toc/blob/main/process/due-diligence-guidelines.md
- Examples:
  - https://github.com/kubevirt/community/issues/96
  - https://github.com/cncf/toc/pull/715/files
- [ ] Document that it is being used successfully in production by at least three independent end users which, in the TOC’s judgement, are of adequate quality and scope. For the definition of an end user, see https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-end-user
- [ ] Have a healthy number of committers.
  - [ ] https://github.com/submariner-io/submariner/pull/1617
  - [x] Remove Miguel from submariner-io GH Org Owners https://github.com/orgs/submariner-io/people.
  - [ ] Remove Steve from https://github.com/orgs/open-cluster-management/teams/team-red-hat
  - [ ] Remove Steve from https://github.com/orgs/open-cluster-management/teams/submariner
  - [x] https://github.com/submariner-io/submariner/issues/1622
  - [ ] Add @dfarrell07 as committer to .github/*?
  - [ ] Add new committers?
- [x] Demonstrate a substantial ongoing flow of commits and merged contributions.
- https://submariner.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m&from=now-2y&to=now-1h
- https://github.com/submariner-io/submariner/pulse
- [x] Since these metrics can vary significantly depending on the type, scope and size of a project, the TOC has final judgement over the level of activity that is adequate to meet these criteria
- [ ] A clear versioning scheme.
  - https://submariner.io/development/release-process/#choosing-versions
  - [ ] Add more clear, user-centric version docs
- [ ] Clearly documented security processes explaining how to report security issues to the project, and describing how the project provides updated releases or patches to resolve security vulnerabilities
  - https://submariner.io/development/security/reporting/
  - [x] https://github.com/submariner-io/submariner/issues/1615
  - [ ] Add docs describing providing updated releases to resolve security vulnerabilities
  - [x] https://github.com/submariner-io/submariner-website/issues/623
- [ ] Specifications must have at least one public reference implementation.
  - [ ] If we add CRDs as a part of https://github.com/submariner-io/enhancements/pull/2/, we should make sure they have a public reference implementation.
  - [ ] Are color codes an issue, since they are still in the CRDs but not really supported?

[CNCF Graduation](https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#graduation-stage):
- [ ] Have committers from at least two organizations.
  - [x] Red Hat
  - [x] SUSE/Rancher (not active, likely shouldn't count)
  - [ ] Active non-Red Hat committers
- [ ] Have achieved and maintained a Core Infrastructure Initiative Best Practices Badge.
  - [x] CII Passing https://bestpractices.coreinfrastructure.org/en/projects/4865#analysis
  - [ ] CII Silver https://bestpractices.coreinfrastructure.org/en/criteria/1
  - [ ] CII Gold https://bestpractices.coreinfrastructure.org/en/criteria/2
- [ ] Have completed an independent and third party security audit with results published of similar scope and quality as the following example (including critical vulnerabilities addressed): https://github.com/envoyproxy/envoy#security-audit and all critical vulnerabilities need to be addressed before graduation.
- [ ] Explicitly define a project governance and committer process. This preferably is laid out in a GOVERNANCE.md file and references an OWNERS.md file showing the current and emeritus committers.
  - https://github.com/submariner-io/submariner/blob/devel/GOVERNANCE.md
  - https://submariner.io/community/contributor-roles/
  - https://github.com/submariner-io/submariner/blob/devel/CODEOWNERS.in
  - [ ] Make a better governance summary
- [ ] Have a public list of project adopters for at least the primary repo (e.g., ADOPTERS.md or logos on the project website). For a specification, have a list of adopters for the implementation(s) of the spec.
  - Example: https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md
  - [x] https://github.com/submariner-io/submariner/pull/1616
- [ ] Receive a supermajority vote from the TOC to move to graduation stage. Projects can attempt to move directly from sandbox to graduation, if they can demonstrate sufficient maturity. Projects can remain in an incubating state indefinitely, but they are normally expected to graduate within two years.

[CII Silver](https://bestpractices.coreinfrastructure.org/en/criteria):
- [x] The project MUST achieve a passing level badge.
  - https://bestpractices.coreinfrastructure.org/en/projects/4865
- [ ] The information on how to contribute MUST include the requirements for acceptable contributions (e.g., a reference to any required coding standard).
  - https://github.com/submariner-io/submariner/blob/devel/.github/PULL_REQUEST_TEMPLATE.md?plain=1
  - https://github.com/submariner-io/submariner/actions/workflows/linting.yml
  - https://submariner.io/development/code-review/
  - [ ] Add Contributor Getting Started guide
- [x] The project SHOULD have a legal mechanism where all developers of non-trivial amounts of project software assert that they are legally authorized to make these contributions. The most common and easily-implemented approach for doing this is by using a Developer Certificate of Origin (DCO), where users add "signed-off-by" in their commits and the project links to the DCO website. However, this MAY be implemented as a  \_ \_Contributor License Agreement (CLA), or other legal mechanism.
  - DCO bot is required for all PRs https://probot.github.io/apps/dco/
  - DCO requirement is documented here: https://submariner.io/community/contributor-roles/#new-contributors
- [ ] The project MUST clearly define and document its project governance model (the way it makes decisions, including key roles).
  - https://github.com/submariner-io/submariner/blob/devel/GOVERNANCE.md
  - [ ] Make a better governance summary
- [x] The project MUST adopt a code of conduct and post it in a standard location.
  - https://github.com/submariner-io/submariner/blob/devel/CODE-OF-CONDUCT.md
  - https://submariner.io/community/code-of-conduct/
- [x] The project MUST clearly define and publicly document the key roles in the project and their responsibilities, including any tasks those roles must perform. It MUST be clear who has which role(s), though this might not be documented in the same way.
    - https://submariner.io/community/contributor-roles/
    - https://github.com/submariner-io/submariner/blob/devel/CODEOWNERS.in
- [x] The project MUST be able to continue with minimal interruption if any one person dies, is incapacitated, or is otherwise unable or unwilling to continue support of the project. In particular, the project MUST be able to create and close issues, accept proposed changes, and release versions of software, within a week of confirmation of the loss of support from any one individual. This MAY be done by ensuring someone e \_ \_lse has any necessary keys, passwords, and legal rights to continue the project. Individuals who run a FLOSS project MAY do this by providing keys in a lockbox and a will providing any needed legal rights (e.g., for DNS names).
- [ ] The project SHOULD have a "bus factor" of 2 or more.
  - [ ] https://github.com/submariner-io/submariner/pull/1623
  - [ ] Document using Submariner Twitter via PRs.
  - [ ] Update Submariner's Twitter password, shared the new one with all/only with Owners and docs committers, and document this practice.
- [ ] The project MUST have a documented roadmap that describes what the project intends to do and not do for at least the next year.
  - https://submariner.io/community/roadmap/
  - [ ] Update the roadmap's future work https://submariner.io/community/roadmap/#future-work
- [x] The project MUST include documentation of the architecture (aka high-level design) of the software produced by the project.
  - https://submariner.io/getting-started/architecture/
- [ ] The project MUST document what the user can and cannot expect in terms of security from the software produced by the project (its "security requirements").
  - https://submariner.io/development/security/containers/
  - [ ] Add more clear security summery
- [x] The project MUST provide a "quick start" guide for new users to help them quickly do something with the software.
  - https://submariner.io/getting-started/quickstart/
- [ ] The project MUST make an effort to keep the documentation consistent with the current version of the project results (including software produced by the project). Any known documentation defects making it inconsistent MUST be fixed. If the documentation is generally current, but erroneously includes some older information that is no longer true, just treat that as a defect, then track and fix as usual.
  - [ ] Audit website and per-repo docs for anything out-of-date
- [x] The project repository front page and/or website MUST identify and hyperlink to any achievements, including this best practices badge, within 48 hours of public recognition that the achievement has been attained.
  - https://github.com/submariner-io/submariner/blob/devel/README.md
- [ ] The project (both project sites and project results) SHOULD follow accessibility best practices so that persons with disabilities can still participate in the project and use the project results where it is reasonable to do so.
  - [ ] https://github.com/submariner-io/submariner-website/issues/268
- [ ] The software produced by the project SHOULD be internationalized to enable easy localization for the target audience's culture, region, or language. If internationalization (i18n) does not apply (e.g., the software doesn't generate text intended for end-users and doesn't sort human-readable text), select "not applicable" (N/A).
- [x] If the project sites (website, repository, and download URLs) store passwords for authentication of external users, the passwords MUST be stored as iterated hashes with a per-user salt by using a key stretching (iterated) algorithm (e.g., Argon2id, Bcrypt, Scrypt, or PBKDF2). If the project sites do not store passwords for this purpose, select "not applicable"
  - NA
- [ ] The project MUST maintain the most often used older versions of the product or provide an upgrade path to newer versions. If the upgrade path is difficult, the project MUST document how to perform the upgrade (e.g., the interfaces that have changed and detailed suggested steps to help upgrade).
  - https://github.com/submariner-io/submariner-operator/actions/workflows/upgrade-e2e.yml
  - [ ] Add CI job that tests latest-subctl with last-release-Submariner https://kubernetes.slack.com/archives/C010RJV694M/p1636450415160700?thread_ts=1636385114.155000&cid=C010RJV694M
  - [ ] Make a 1.0.0 release
- [x] The project MUST use an issue tracker for tracking individual issues.
  - https://github.com/submariner-io/submariner/issues
- [x] The project MUST give credit to the reporter(s) of all vulnerability reports resolved in the last 12 months, except for the reporter(s) who request anonymity. If there have been no vulnerabilities resolved in the last 12 months, select "not applicable".
  - NA
- [x] The project MUST have a documented process for responding to vulnerability reports.
  - https://submariner.io/development/security/reporting/
- [ ] The project MUST identify the specific coding style guides for the primary languages it uses, and require that contributions generally comply with it.
- [x] The project MUST automatically enforce its selected coding style(s) if there is at least one FLOSS tool that can do so in the selected language(s).
  - https://github.com/submariner-io/submariner/blob/devel/.golangci.yml
- [ ] Build systems for native binaries MUST honor the relevant compiler and linker (environment) variables passed in to them (e.g., CC, CFLAGS, CXX, CXXFLAGS, and LDFLAGS) and pass them to compiler and linker invocations. A build system MAY extend them with additional flags; it MUST NOT simply replace provided values with its own.
- [ ] The build and installation system SHOULD preserve debugging information if they are requested in the relevant flags (e.g., "install -s" is not used).
- [ ] The build system for the software produced by the project MUST NOT recursively build subdirectories if there are cross-dependencies in the subdirectories.
- [ ] The project MUST be able to repeat the process of generating information from source files and get exactly the same bit-for-bit result.
- [ ] The project MUST provide a way to easily install and uninstall the software produced by the project using a commonly-used convention.
  - https://submariner.io/operations/deployment/subctl/
  - [ ] Uninstall automation https://github.com/submariner-io/enhancements/issues/50
- [ ] The installation system for end-users MUST honor standard conventions for selecting the location where built artifacts are written to at installation time. For example, if it installs files on a POSIX system it MUST honor the DESTDIR environment variable. If there is no installation system or no standard convention, select "not applicable" (N/A).
- [ ] The project MUST provide a way for potential developers to quickly install all the project results and support environment necessary to make changes, including the tests and test environment. This MUST be performed with a commonly-used convention.
  - https://submariner.io/development/building-testing/
  - [ ] Make building/testing changes to multiple repos easier and more automated
- [ ] The project MUST list external dependencies in a computer-processable way.
- [ ] Projects MUST monitor or periodically check their external dependencies (including convenience copies) to detect known vulnerabilities, and fix exploitable vulnerabilities or verify them as unexploitable.
  - [ ] Add dependency security scanning with https://github.com/sonatype-nexus-community/nancy
- [ ] The project MUST either: make it easy to identify and update reused externally-maintained components; or use the standard components provided by the system or programming language. Then, if a vulnerability is found in a reused component, it will be easy to update that component.
- [ ] The project SHOULD avoid using deprecated or obsolete functions and APIs where FLOSS alternatives are available in the set of technology it uses (its "technology stack") and to a supermajority of the users the project supports (so that users have ready access to the alternative).
- [x] An automated test suite MUST be applied on each check-in to a shared repository for at least one branch. This test suite MUST produce a report on test success or failure.
  - https://github.com/submariner-io/submariner/tree/devel/.github/workflows
- [ ] The project MUST add regression tests to an automated test suite for at least 50% of the bugs fixed within the last six months.
- [ ] The project MUST have FLOSS automated test suite(s) that provide at least 80% statement coverage if there is at least one FLOSS tool that can measure this criterion in the selected language.
- [x] The project MUST have a formal written policy that as major new functionality is added, tests for the new functionality MUST be added to an automated test suite
  - https://submariner.io/development/code-review/#test-new-functionality
- [x] The project MUST include, in its documented instructions for change proposals, the policy that tests are to be added for major new functionality.
  - https://github.com/submariner-io/submariner/blob/devel/.github/PULL_REQUEST_TEMPLATE.md?plain=1
- [ ] Projects MUST be maximally strict with warnings in the software produced by the project, where practical.
- [ ] The project MUST implement secure design principles (from "know_secure_design"), where applicable.
- [x] The default security mechanisms within the software produced by the project MUST NOT depend on cryptographic algorithms or modes with known serious weaknesses (e.g., the SHA-1 cryptographic hash algorithm or the CBC mode in SSH).
  - The defaults are specified by the tools we use: Libreswan for IPsec, WireGuard, Kubernetes; all of these follow industry best practices.
- [ ] The project SHOULD support multiple cryptographic algorithms, so users can quickly switch if one is broken. Common symmetric key algorithms include AES, Twofish, and Serpent. Common cryptographic hash algorithm alternatives include SHA-2 (including SHA-224, SHA-256, SHA-384 AND SHA-512) and SHA-3.
- [ ] The project MUST support storing authentication credentials (such as passwords and dynamic tokens) and private cryptographic keys in files that are separate from other information (such as configuration files, databases, and logs), and permit users to update and replace them without code recompilation. If the project never processes authentication credentials and private cryptographic keys, select "not applicable" (N \_/A).
- [ ] The software produced by the project SHOULD support secure protocols for all of its network communications, such as SSHv2 or later, TLS1.2 or later (HTTPS), IPsec, SFTP, and SNMPv3. Insecure protocols such as FTP, HTTP, telnet, SSLv3 or earlier, and SSHv1 SHOULD be disabled by default, and only enabled if the user specifically configures it. If the software produced by the project does not support network communications, select "not applicable" (N/A).
- [ ] The software produced by the project SHOULD, if it supports or uses TLS, support at least TLS version 1.2. Note that the predecessor of TLS was called SSL. If the software does not use TLS, select "not applicable" (N/A).
- [ ] The software produced by the project MUST, if it supports TLS, perform TLS certificate verification by default when using TLS, including on subresources. If the software does not use TLS, select "not applicable" (N/A).
- [ ] The software produced by the project MUST, if it supports TLS, perform certificate verification before sending HTTP headers with private information (such as secure cookies). If the software does not use TLS, select "not applicable" (N/A).
- [ ] The project MUST cryptographically sign releases of the project results intended for widespread use, and there MUST be a documented process explaining to users how they can obtain the public signing keys and verify the signature(s). The private key for these signature(s) MUST NOT be on site(s) used to directly distribute the software to the public.
- [ ] It is SUGGESTED that in the version control system, each important version tag (a tag that is part of a major release, minor release, or fixes publicly noted vulnerabilities) be cryptographically signed and verifiable as described in signed_releases.
- [ ] The project results MUST check all inputs from potentially untrusted sources to ensure they are valid (an *allowlist*), and reject invalid inputs, if there are any restrictions on the data at all.
- [ ] Hardening mechanisms SHOULD be used in the software produced by the project so that software defects are less likely to result in security vulnerabilities.
- [ ] The project MUST provide an assurance case that justifies why its security requirements are met. The assurance case MUST include: a description of the threat model, clear identification of trust boundaries, an argument that secure design principles have been applied, and an argument that common implementation security weaknesses have been countered.
- [x] The project MUST use at least one static analysis tool with rules or approaches to look for common vulnerabilities in the analyzed language or environment, if there is at least one FLOSS tool that can implement this criterion in the selected language.
  - golangci-lint/gosec https://github.com/submariner-io/submariner/blob/71a2e1103e1ffd09366a8f097a2326b78d18fc8c/.golangci.yml#L64
- [x] If the software produced by the project includes software written using a memory-unsafe language (e.g., C or C++), then at least one dynamic tool (e.g., a fuzzer or web application scanner) MUST be routinely used in combination with a mechanism to detect memory safety problems such as buffer overwrites. If the project does not produce software written in a memory-unsafe language, choose "not applicable" (N/A).
  - NA

[CII Gold](https://bestpractices.coreinfrastructure.org/en/criteria)
- [ ] The project MUST achieve a silver level badge.
- [x] The project MUST have a "bus factor" of 2 or more.
- [ ] The project MUST have at least two unassociated significant contributors.
  - [ ] Add non-Red Hat significant contributors
- [x] The project MUST include a copyright statement in each source file, identifying the copyright holder (e.g., the [project name] contributors).
  - https://github.com/submariner-io/submariner/blob/71a2e1103e1ffd09366a8f097a2326b78d18fc8c/.licenserc.json#L21
  - https://github.com/submariner-io/submariner/blob/71a2e1103e1ffd09366a8f097a2326b78d18fc8c/.github/workflows/linting.yml#L68
- [x] The project MUST include a license statement in each source file. This MAY be done by including the following inside a comment near the beginning of each file: SPDX-License-Identifier: [SPDX license expression for project].
  - https://github.com/submariner-io/submariner/blob/71a2e1103e1ffd09366a8f097a2326b78d18fc8c/.licenserc.json#L21
- [x] The project's source repository MUST use a common distributed version control software (e.g., git or mercurial).
  - git
- [ ] The project MUST clearly identify small tasks that can be performed by new or casual contributors.
  - https://github.com/submariner-io/submariner-operator/issues?q=label%3A%22good+first+issue%22+
  - [ ] Label more issues with good-first-issue
- [ ] The project MUST require two-factor authentication (2FA) for developers for changing a central repository or accessing sensitive data (such as private vulnerability reports). This 2FA mechanism MAY use mechanisms without cryptographic mechanisms such as SMS, though that is not recommended.
  - [x] https://github.com/submariner-io/submariner-website/issues/623
- [ ] The project's two-factor authentication (2FA) SHOULD use cryptographic mechanisms to prevent impersonation. Short Message Service (SMS) based 2FA, by itself, does NOT meet this criterion, since it is not encrypted.
  - [x] https://github.com/submariner-io/submariner-website/issues/623
- [x] The project MUST document its code review requirements, including how code review is conducted, what must be checked, and what is required to be acceptable.
  - https://submariner.io/development/code-review/
- [x] The project MUST have at least 50% of all proposed modifications reviewed before release by a person other than the author, to determine if it is a worthwhile modification and free of known issues which would argue against its inclusion
  - https://submariner.io/development/code-review/#two-non-author-committer-approvals-required
- [ ] The project MUST have a reproducible build. https://reproducible-builds.org/
- [x] A test suite MUST be invocable in a standard way for that language.
  - https://submariner.io/development/building-testing/#unit-tests
  - https://github.com/submariner-io/shipyard/blob/edbecd0ba223aa80253664c1c9bee290e4a3aec1/scripts/shared/unit_test.sh#L29
- [x] The project MUST implement continuous integration, where new or changed code is frequently integrated into a central code repository and automated tests are run on the result.
  - https://github.com/submariner-io/submariner/tree/devel/.github/workflows
- [ ] The project MUST have FLOSS automated test suite(s) that provide at least 90% statement coverage if there is at least one FLOSS tool that can measure this criterion in the selected language.
- [ ] The project MUST have FLOSS automated test suite(s) that provide at least 80% branch coverage if there is at least one FLOSS tool that can measure this criterion in the selected language.
- [ ] The software produced by the project MUST support secure protocols for all of its network communications, such as SSHv2 or later, TLS1.2 or later (HTTPS), IPsec, SFTP, and SNMPv3. Insecure protocols such as FTP, HTTP, telnet, SSLv3 or earlier, and SSHv1 MUST be disabled by default, and only enabled if the user specifically configures it.
- [ ] The software produced by the project MUST, if it supports or uses TLS, support at least TLS version 1.2. Note that the predecessor of TLS was called SSL. If the software does not use TLS, select "not applicable" (N/A).
- [ ] The project website, repository (if accessible via the web), and download site (if separate) MUST include key hardening headers with nonpermissive values.
- [ ] The project MUST have performed a security review within the last 5 years. This review MUST consider the security requirements and security boundary.
- [ ] Hardening mechanisms MUST be used in the software produced by the project so that software defects are less likely to result in security vulnerabilities.
- [ ] The project MUST apply at least one dynamic analysis tool to any proposed major production release of the software produced by the project before its release.
- [ ] The project SHOULD include many run-time assertions in the software it produces and check those assertions during dynamic analysis.
