### ISSUE TITLE
[EPIC] Support for VPC Peering

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#64]
**What would you like to be added**:
Proposal is to add support for VPC Peering between clusters deployed with same cloud provider.

**Why is this needed**:
When all cluster are deployed within the same cloud provider, VPC Peering provides secure networking between them. In such scenario one can use VxLan Cable driver for better performance without the IPSec overhead. 

**Work Items**

- [ ] Add generic API for VPC Peering (cloud-prepare)
  - [ ] https://github.com/submariner-io/cloud-prepare/pull/190
- [ ] Add code for VPC Peering in AWS (cloud-prepare)
- [ ] Add code for VPC Peering in GCP (cloud-prepare)
- [ ] Add code for VPC Peering in Azure? (cloud-prepare)
- [ ] Add subctl command to add VPC peering (submariner-operator)
  - [ ] https://github.com/submariner-io/submariner-operator/pull/1794
- [ ] Add VPC Peering support to submariner-addon (submariner-addon)
- [ ] Add support for VPC peering in ACM UI (console)
- [ ] Add user prompt for VPC Peering not available if all clusters are not in same cloud provider. (console)
- [ ] Enable VPC Peering by default when using VxLan driver and all clusters on same provider.
- [ ] Add a user prompt when adding a new cluster from a different provider to a clusterset already using VPC Peering that different provider can't be added coz VPC Peering is already enabled.

**Comment by tpantelis** [comment]
We had decided to put the epics in the enhancements project.

**Comment by nyechiel** [comment]
> We had decided to put the epics in the enhancements project.

I moved it over using https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by nyechiel** [comment]
- With the current Submariner model, within a ClusterSet, all the participating clusters must use the same cable driver. This also means that for this use case, within a ClusterSet we expect all clusters to be interconnected via VPC Peering connections in a full mesh - and all of the Submariner connections must use the same driver (typically VXLAN). @sridhargaddam while VXLAN makes most sense for this kind of use-case, I don't think we need to force the user to use it on top of VPC Peering, i.e we should also let users deploy IPsec on top of VPC Peering if they wish to do so. Would you agree?

- This is about enabling VPC Peering connection within one single cloud provider, i.e all clusters within the ClusterSet need to be on the same provider (for e.g GCP, **or** AWS, **or** Azure, etc.). The classic use case is for each cluster to be on a different region. 

- Assuming we can get it done for AWS, I think we should also aim to implement GCP for OCM 2.5/Submariner 0.12. Once we figure out the UX with `subctl`, I hope the addon/UI work will be more straight forward. For reference, here is the GCP blog from Raffa: https://cloud.redhat.com/blog/geographically-distributed-stateful-workloads-part-four-kafka

- There is one additional use-case where the user deploys the VPC Peering outside of our control. We should also address it.

- On on-prem setups (for e.g bare-metal, OpenStack, VMware), VXLAN is useful without a VPC Peering underneath. We need to ensure that there is an option to simply pick VXLAN without a VPC Peering like we have today.

**Comment by sridhargaddam** [comment]
> * With the current Submariner model, within a ClusterSet, all the participating clusters must use the same cable driver. This also means that for this use case, within a ClusterSet we expect all clusters to be interconnected via VPC Peering connections in a full mesh - and all of the Submariner connections must use the same driver (typically VXLAN). @sridhargaddam while VXLAN makes most sense for this kind of use-case, I don't think we need to force the user to use it on top of VPC Peering, i.e we should also let users deploy IPsec on top of VPC Peering if they wish to do so. Would you agree?

+1. When VPC Peering is used, the default Cable-driver can be shown as VxLAN, but we can give an option to the user to override it.

> * On on-prem setups (for e.g bare-metal, OpenStack, VMware), VXLAN is useful without a VPC Peering underneath. We need to ensure that there is an option to simply pick VXLAN without a VPC Peering.

+1 with an assumption that all such clusters are directly reachable over their private ips and inter-cluster traffic does not enter a public domain.

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub today, it seems like there are still open questions:

* What exactly is Submariner supposed to do in this use-case - @mkolesnik
* If we had a ClusterSet in AWS doing VPC peering, and we add a cluster from GCP that doesn't support VPC peering, what do we do? @sridhargaddam 
* This might be more useful once we have connectivity policies, where we can exactly say which clusters are connected to which.

Seems like it needs more discussion, planning. Great to do soon, but moving to the backlog for now.

**Comment by nyechiel** [comment]
Related design proposal: https://github.com/submariner-io/enhancements/pull/121

**Comment by maayanf24** [comment]
Talked on the planning call - not a priority for now
