### ISSUE TITLE
Epic: rebuild the Submariner operator using current best practices

### ISSUE THREAD

**Issue by skitt** [submariner-io/enhancements#81]
## Epic Description

The operator was built using an old version of the [Operator SDK](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/). This causes a number of problems:

* our code (in particular, metrics setup) relies on an old version of the Operator framework, which is incompatible with current versions of the Kubernetes libraries
* we’re missing out on features supported by newer versions of the SDK (such as healthchecks)

We need to upgrade our operator to use the current Operator SDK, following [the migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/migration/).

Depends on #89 

## Related changes

https://github.com/stolostron/submariner-addon/issues/318
https://github.com/submariner-io/submariner-operator/issues/1105
https://github.com/submariner-io/submariner-operator/issues/1415
https://github.com/submariner-io/submariner-operator/issues/1824

## Acceptance Criteria

The operator’s Operator framework dependencies are up-to-date, and all tests pass.

## Definition of Done (Checklist)

* [x] Code complete
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [x] Deploy using Helm
* [x] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [x] Run subctl verify, diagnose and gather
* ~~[ ] Uninstall~~
* ~~[ ] Troubleshooting (gather/diagnose) added~~
* ~~[ ] Documentation added~~
* ~~[ ] Release notes added~~

## Work Items
An operator was written from scratch following the [official operator tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/). The code was pushed on a fork as a [PR](https://github.com/Jaanki/submariner-operator/pull/10). This PR was then used as a reference to make required changes. 

The operator-sdk version is upgraded to 1.23.0. [Migration guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/) was followed to pin versions for dependencies.

1. Depends on https://github.com/submariner-io/submariner-operator/pull/2158
2. Update versions of various dependencies used
     1. Depends on https://github.com/submariner-io/submariner-operator/pull/2210
     2. Depends on https://github.com/submariner-io/submariner-operator/pull/2179
3. Depends on https://github.com/submariner-io/submariner-operator/pull/2178
4. Depends on https://github.com/submariner-io/submariner-operator/pull/2211
5. Depends on https://github.com/submariner-io/submariner-operator/pull/2204
6. Depends on https://github.com/submariner-io/submariner-operator/pull/2199
7. Depends on https://github.com/submariner-io/submariner-operator/pull/2180
8. Depends on https://github.com/submariner-io/submariner-operator/pull/2230
9. Update bundle in `operatorHub'(https://github.com/k8s-operatorhub/community-operators)
10. and here? https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators

**Comment by Jaanki** [comment]
NOTE: if #89 is approved, it should be done first.

**Comment by dfarrell07** [comment]
As Andrew McNamara pointed out on Slack, this will have implications downstream that we shouldn't forget.

**Comment by arewm** [comment]
I was about to make some changes to this in order to remove the need for a workaround for https://github.com/operator-framework/operator-sdk/issues/5760, but stopped when I realized there may be additional implications of an update in one place.

One change that I was going to make was with `PROJECT` to have the following contents:
```
domain: submariner.io
repo: github.com/submariner-io/submariner-operator
projectName: submariner
layout:
- go.kubebuilder.io/v2
plugins:
  go.sdk.operatorframework.io/v2-alpha: {}
version: "3"
multigroup: true
```

**Comment by nyechiel** [comment]
@tpantelis @Jaanki so this is no longer planned for 0.13?

**Comment by tpantelis** [comment]
> @tpantelis @Jaanki so this is no longer planned for 0.13?

No there's not enough time to get the PRs pushed and reviewed by Fri.
