### ISSUE TITLE
Epic: Support OCP with submariner on Azure

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#87]
**What would you like to be added**:
Proposal is to fully support connecting multiple OCP clusters on Azure using Submariner.

**Why is this needed**:
Aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

**Work Items**

- [x] Test and confirm manual steps to get Azure with submariner working
- [x] Add API in cloud-prepare to create and return client with Azure credentials
- [x] Add support for load balancer mode
- [x] submariner-io/cloud-prepare/issues/289
- [x] submariner-io/submariner-website#766
- [x] submariner-io/subctl#17
- [x] submariner-io/submariner-operator#1762
- [x] submariner-io/submariner-operator#1763
- [x] submariner-io/cloud-prepare#22

**Comment by dfarrell07** [comment]
Discussion about this on PR Scrub:

* This doesn't seem to be size:med, it will take a lot of time with all the testing, much more than a sprint (moved to large)
* Do we need an EP for this? It was started before this release, is already WIP (but this might not be a good reason). This isn't much of a design change, is basically an extension of what we already do.

**Comment by maayanf24** [comment]
@aswinsuryan - Can we close the epic now?
