### ISSUE TITLE
[EPIC] Debuggability and Troubleshooting support in OCM

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#88]
---
name: Debuggability and Troubleshooting
about: Improving debuggability and troubleshooting for submariner deplyments in general, OCM in particular
labels: epic

---

## Epic Description
Current documentation on Sumariner.io - [Troubleshooting docs](https://submariner.io/operations/troubleshooting/) covers the basic manual steps and how to run subctl diagnose and gather. What more needs to be done? Aim is to make it easy for support teams to troubleshoot and resolve the problems, or capture relevant information if unable to resolve.

## Acceptance Criteria
TBD

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

* [x] OCM - Refactor `subctl` code to reuse `gather` and `diagnose` like a library
  * [x] https://github.com/submariner-io/enhancements/pull/60
  * [x] https://github.com/submariner-io/submariner-operator/pull/1812
* [x] #95 
* [x] #93 
  * [x] https://github.com/stolostron/backlog/issues/19294
* [x] #94
  * [x] https://github.com/stolostron/submariner-addon/pull/261
  * [x] https://github.com/stolostron/backlog/issues/19295
  * [ ] https://github.com/stolostron/submariner-addon/pull/295
* [ ] OCP `must-gather` - Add `gather` to [OCP must-gather](https://github.com/openshift/must-gather)
* [x] CI/CD - Add `subctl diagnose` to CI/CD in case of any test failure
  * [x] https://github.com/submariner-io/shipyard/pull/712
* [ ] CI/CD - Use `subctl gather` in CI/CD post-mortem in case of any test failure

**Comment by vthapar** [comment]
Broke up this EPIC into smaller sub epics. Progress will be tracked in individual EPICs, retaining this for historical purposes.

**Comment by maayanf24** [comment]
@vthapar - can we close this epic now?
