### ISSUE TITLE
Epic: Move subctl to its own repo

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/enhancements#89]
## Epic Description
subctl, soon to be a library itself, should be moved out of submariner-operator repo to its own repo. Everything specific to the subctl is moved to the subctl repo. Operator repo depends on the subctl repo. Operator repo should contain things that the operator framework generates/ needs. This is an alternative to the previous proposal of moving bundles out of the operator repo.

**Pros:**
1. both subctl and operator require different set of dependencies which might conflict will improving subctl/operator. For eg, subctl can't be `go install`-ed currently because the operator dependencies don't allow it.
2. operator framework upgrades would be simpler.
3. its logically correct to separate operator and a library as they are 2 different deliverables and provides different ways to install Submariner.
4. Testing criterias are also different. We don't need subctl related GHAs for operator and vice versa.
5. Development approach is also different. 1 is a CLI and another is a framework.
6. submariner-addon integration might be simplified.

**Cons:**
1. A new repo to maintain
2. Might add a new phase to the automated release process

## Acceptance Criteria
All of the subctl related code/GHAs are out of operator repo and in the new subctl repo.

## Definition of Done (Checklist)
* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
Depends on https://github.com/submariner-io/enhancements/issues/114

- [x] Create a new `subctl` repository and copy all the contents from `submariner-operator` repository.

### On `subctl` repository

- [x] https://github.com/submariner-io/subctl/issues/3

### On `submariner-operator` repository
Depends on https://github.com/submariner-io/submariner-operator/issues/2030

- [x] https://github.com/submariner-io/submariner-operator/issues/2030

### On `get.submariner.io` repository

- [x] https://github.com/submariner-io/get.submariner.io/issues/21

### On `submariner-website` repository

- [x]  https://github.com/submariner-io/submariner-website/issues/743

### Release process

- [x] https://github.com/submariner-io/releases/issues/340

### External dependencies

- [ ] Add `subctl` dependency in `submariner-addon`.
