### ISSUE TITLE
[EPIC]:  Connection status in OCM UI

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#93]
## Epic Description
Currently OCM UI doesn't show connection status in its own UI. It shows up as part of ManagedClusterAddOn status. It is not very intuitive for user to know which cluster connections are in connecting or error states. With topology view available in OCM 2.6, it should be used to display multicluster connection information to user.

Refer https://github.com/submariner-io/enhancements/issues/88

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Documentation added
* [ ] Release notes added

## Work Items
* [ ] OCM - Add Connection Status to UI
  * [ ] Add ConnectionStatus CRD or such a field to SubmarinerConfig Status in submariner addon.
  * [x] https://github.com/stolostron/backlog/issues/19294

## Dependencies
This requires topology view to be available in OCM UI. Also requires some design discussions with UI team on how to model ConnectionStatus CRD so it can be used by UI in a scaleable way.

**Comment by vthapar** [comment]
Closing for now. Revisit when we have more clarity on what needs to be done in submariner.
