### ISSUE TITLE
[EPIC] OCM - Add option to run diagnose in UI

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#94]
## Epic Description

`subctl diagnose` is a CLI tool used to troubleshoot submariner deployments. But no such tools are available from the OCM UI. Add option in OCM UI to run diagnostics.

Refer submariner-io/submariner-operator#88 

## Acceptance Criteria
TBD

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using ACM/OCM addon
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
  * [x] https://github.com/stolostron/submariner-addon/pull/261
  * [x] https://github.com/stolostron/backlog/issues/19295
  * [ ] https://github.com/stolostron/submariner-addon/pull/295
  * [x] submariner-io/subctl#48

**Comment by nyechiel** [comment]
Most of it really resides in ACM/stolostron repo.
