### ISSUE TITLE
[EPIC] Add option to gather submariner logs from OCM UI

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#95]
## Epic Description

`subctl gather` is a CLI tool used to gather logs and other data from submariner deployments. But no such tools are available from the OCM UI. Add option in OCM UI to run gather logs.

Refer #88 

## Acceptance Criteria
TBD

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using ACM/OCM addon
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items
  * [ ] Addon - Run `subctl gather` Job on the cluster
  * [ ] UI - Add option to run gather from
  * [ ] UI - Add option to collect logs from a gather run
  * [ ] UI - Provide option to run gather after a fail diagnostics when running diagnostics

**Comment by vthapar** [comment]
Close for now, revisit when more clarity on what needs to be done on submariner.
