### ISSUE TITLE
Get Submariner/OVN-Kubernetes Integration to a Production Ready State 

### ISSUE THREAD

**Issue by astoycos** [submariner-io/enhancements#96]
## Epic Description

[OVN-Kubernetes](https://github.com/ovn-org/ovn-kubernetes) is one of the two CNI's supported by RedHat Openshift, and will soon become the sole CNI for the Kubernetes distribution.  Submariner supports the CNI via the [OVN-Kubernetes specific NetworkPluginSyncer](https://github.com/submariner-io/submariner/tree/devel/pkg/networkplugin-syncer/handlers/ovn), however the design is more of a POC and currently non-functional with recent OVN-K versions.  Many more steps need to be taken in order to  ensure the integration is bug-free and ready for production environments, this epic will track the work that is needed to get the integration to such a state. 

## Acceptance Criteria

Submariner's ability to connect clusters utilizing the OVN-Kubernetes CNI is 100% functional with current OVN-K builds, and the correct CI infrastructure has been put into place in order to ensure the continued functionality of the integration.  

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

## Work Items

- [ ] Fix Existing Bugs and Issues with OVN-Kubernetes CNI Integration 
  - [x] https://github.com/submariner-io/shipyard/issues/703
  - [x] https://github.com/submariner-io/submariner/issues/1278
  - [x] https://github.com/submariner-io/submariner/issues/1101
  - [x] https://github.com/submariner-io/submariner/issues/1625
  - [x] https://github.com/submariner-io/submariner/issues/1631
- [x] Broken service connectivity across cluster with ovn-kubernetes https://github.com/submariner-io/submariner/issues/1608 
- [ ] Update Documentation to be more in-depth 
  - [x] [Clarify the requirement for opening UDP/4800 port for OVNK](https://github.com/submariner-io/submariner-website/pull/780)
  - [x] https://github.com/submariner-io/submariner-website/pull/699 
- [ ] Add CI to ensure continued functionality 
   - [ ] Have testing to ensure updates to OVN-Kubernetes does not break the integration 
   - [ ] Have testing to ensure updates to Submariner does not break the integration 
- [ ] Present the current OVN networkPluginSyncer Architecture to the OVN-Kubernetes upstream community, looking for possible improvements

**Comment by sridhargaddam** [comment]
The following PR implements the necessary support for OCP 4.11 - https://github.com/submariner-io/submariner/pull/1689

**Comment by nyechiel** [comment]
@vthapar @sridhargaddam  can you please review the issues linked to this epic? is there anything we want to still target to 0.13?

**Comment by maayanf24** [comment]
@vthapar @sridhargaddam - can you report individual issues to track the remaining work and close the epic?

**Comment by nyechiel** [comment]
Closing now that 0.13 was shipped. Other gaps (e.g, Globalnet support) should be tracked separately.
