### ISSUE TITLE
Submariner Globalnet Support with OVN-Kubernetes CNI 

### ISSUE THREAD

**Issue by astoycos** [submariner-io/enhancements#97]
## Epic Description

The current implementation of Globalnet Controller works with iptables based kubeproxy. We have to add support for clusters that use OVN as the network-plugin driver.

## Acceptance Criteria

The Globalnet feature functions correctly when using Submariner with the OVN-Kubernetes CNI. 

## Definition of Done (Checklist)

* [x] Code complete
* [x] Relevant metrics added
* [x] The acceptance criteria met
* [x] Unit/e2e test added & pass
* [x] CI jobs pass
* [x] Deployed using cloud-prepare+subctl
* [x] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [x] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [x] Run subctl verify, diagnose and gather
* [x] Uninstall
* [x] Troubleshooting (gather/diagnose) added
* [x] Documentation added
* [x] Release notes added

## Work Items
- [x] [Enhancement PR: Globalnet support for OVN Kubernetes deployments](https://github.com/submariner-io/enhancements/pull/130)
- [x] [Missing rule in SUBMARINER-POSTROUTING chain](https://github.com/submariner-io/submariner/issues/1981)
- [x] [Missing default route in table 150 on all the worker nodes](https://github.com/submariner-io/submariner/issues/1982)
- [x] [Redirect the ingress traffic to a cluster via the submariner_router](https://github.com/submariner-io/submariner/issues/1983)
- [x] [Fix logical routes programmed in submariner_router](https://github.com/submariner-io/submariner/issues/1984)
- [x] [Race condition in ovn routeagent handler](https://github.com/submariner-io/submariner/issues/2004)
- [x] [Documentation](https://github.com/submariner-io/submariner-website/issues/830)

**Comment by maayanf24** [comment]
Only item left to do is documentation

**Comment by sridhargaddam** [comment]
Documentation is updated as part of the following PR: https://github.com/submariner-io/submariner-website/issues/830
